title: fdrx puerh notes
email: fdrx-puerh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fdrx.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fdrx
github_username:  fdrx
img_path: "/assets/images/posts/"
maps_path: "/assets/images/maps/"
collections:
  maps:
    output: true
    permalink: /maps/:title

# Build settings
theme: null
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      category: sheng
      shape: beeng
