title: fdrx puerh notes
email: 
description: "fdrx Puerh tea notes, blog, reviews, maps, and guides to puerh tea regions, areas and villages."
keywords: ["puerh tea", "puerh blog", "puerh reviews", "puerh maps", "puerh villages", "tea regions", "tea notes", "fdrx"]
url: "https://fdrx.github.io"
baseurl: ""
author: "fdrx"
github_username:  fdrx
twitter_username: 
og_image: "/assets/img/site/default-og-image.jpg"
css_path: "/assets/css/"
ico_path: "/assets/ico/"
site_path: "/assets/img/site/"
img_path: "/assets/img/posts/"
maps_path: "/assets/img/maps/"
about_path: "/assets/img/about/"
thumbs_path: "/assets/img/thumbs/"
collections:
  maps:
    output: true
    permalink: /maps/:title
# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      category: sheng
      shape: beeng
      lastmod: 2012-12-12
feed:
  email: false
sitemap:
  lastmod: true